# These are supported funding model platforms

github: Alexa Espina
patreon: Alexa Espina
open_collective: # Replace with a single Open Collective username
ko_fi: Alexa Espina
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: Alexa Espina
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://wise.com/pay#c5WqArsOsqN1YtRJIZ3W9RiN910']
